version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  # TODO: Migrate and seed DB
  api:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - with-api
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 4000
      NODE_ENV: production
      SECRET: oo6iP6dQRC/qm2WlUn3Tej+LocObV801
      DATABASE_URL: postgresql://postgres:password@postgres:5432
      REDIS_URL: redis://:@redis:6379
      INTROSPECTION: true
    ports:
      - 4000:4000
