version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
